version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: federation_db_mysql
    ports:
      - "3306:3306"
    volumes:
      - D:\DB\federe\mysql_data:/var/lib/mysql
    networks:
      - federation_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: federation_db_postgres
    ports:
      - "5438:5432"
    volumes:
      - D:\DB\federe\postgres_data:/var/lib/postgresql/data
    networks:
      - federation_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: password
      ORACLE_DATABASE: federation_db_oracle
    volumes:
      - D:\DB\federe\oracle_data:/opt/oracle/oradata
    networks:
      - federation_network
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "/nolog", "whenever sqlerror exit failure;", "connect system/oracle_password@//localhost:1521/XEPDB1", "select 1 from dual;"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
  postgres_data:
  oracle_data:
    
networks:
  federation_network: