services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: federation_db_mysql
    ports:
      - "3306:3306"
    volumes:
      - ../data_schema/tetouan/mysql_data:/var/lib/mysql
    networks:
      - federation_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: federation_db_postgres
    ports:
      - "5432:5432"
    volumes:
      - ../data_schema/tanger/postgres_data:/var/lib/postgresql/data
    networks:
      - federation_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  oracle-db:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: oracle-db
#    build:
#      context: ./dockerfile/oracle
    ports:
      - "1521:1521"
      - "5505:5500"
    environment:
      ORACLE_PWD: password  # Mot de passe pour l'utilisateur SYS et SYSTEM
      ORACLE_SID: ORCL  # SID de la base de données Oracle
      ORACLE_PDB: federation_db_oracle  # PDB de la base de données Oracle
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - ../data_schema/rabat/oracle_data:/opt/oracle/oradata
#      - ./config/hs/admin:/opt/oracle/product/21c/hs/admin  # Configuration de l'administration
#      - ./config/odbc.ini:/etc/odbc.ini  # Fichier de configuration ODBC pour Oracle
#      - ./config/odbcinst.ini:/etc/odbcinst.ini  # Fichier de configuration des drivers ODBC
#      - ./scripts/install_odbc.sh:/docker-entrypoint-initdb.d/install_odbc.sh  # Script d'installation ODBC
    networks:
      - federation_network
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "/nolog", "whenever sqlerror exit failure;", "connect system/oracle_password@//localhost:1521/federation_db_oracle", "select 1 from dual;"]
      interval: 30s
      timeout: 10s
      retries: 3
#    entrypoint: ["/bin/bash", "/docker-entrypoint-initdb.d/install_odbc.sh"]  # Exécution du script d'installation ODBC lors du démarrage du conteneur

volumes:
  mysql_data:
  postgres_data:
  oracle_data:
    
networks:
  federation_network:
    driver: bridge  # Utilisation du driver de réseau bridge (réseau interne Docker)